### ISSUE TITLE
help!help!...android.system.ErrnoException

### ISSUE THREAD

**Issue by qp910** [ligerbots/Steamworks2017Vision#1]
<img width="667" alt="default" src="https://cloud.githubusercontent.com/assets/8297287/23641318/c988ea40-032d-11e7-906e-8c0c672e7a7c.png">
  Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                 at libcore.io.Posix.open(Native Method)
                                                 at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                 at libcore.io.IoBridge.open(IoBridge.java:438)
                                                 at java.io.FileInputStream.<init>(FileInputStream.java:76) 
                                                 at java.io.FileInputStream.<init>(FileInputStream.java:103) 
                                                 at java.io.FileReader.<init>(FileReader.java:66) 
                                                 at erik.android.vision.visiontest.Parameters.initPurpose(Parameters.java:88) 
                                                 at erik.android.vision.visiontest.Communications.initNetworkTables(Communications.java:53) 
                                                 at erik.android.vision.visiontest.Camera2Activity.onCreate(Camera2Activity.java:279) 
                                                 at android.app.Activity.performCreate(Activity.java:6323) 
                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108) 
                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385) 
                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492) 
                                                 at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358) 
                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                 at android.os.Looper.loop(Looper.java:148) 
                                                 at android.app.ActivityThread.main(ActivityThread.java:5458) 
                                                 at java.lang.reflect.Method.invoke(Native Method) 
                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by xeniarose** [comment]
I'm pleasantly surprised that someone is actually interested in what we're doing. If your team is seriously planning on using our vision app for this competition season, we'd love to hear about it! You can contact us using the email listed on our github page (https://github.com/ligerbots)

To address the issue: There are three required files that you should copy to `/storage/emulated/0` (excuse the bad naming for the moment). I realized I hadn't checked them in before. They should now be in the root folder of the repository
- cameraparameters.json: The camera matrix and distortion vector required to generate 3D coordinates. Currently contains parameters for the Nexus 5 camera
- camerasettings.json: Camera exposure time and sensitivity. Currently contains arbitrary values that work in our shop but will need to be tuned on the field
- purpose.txt: What the phone is supposed to do. Enter `boiler` for boiler vision (currently not working well) and `gearlift` for gear lift vision (works pretty well).

Note: If you try to connect *two* stock Nexus 5s to the roboRIO, USB tethering will not work! We are running a custom-built AOSP ROM to get two phones to connect and I have not published the necessary source changes yet. However, if you only plan on one phone, it will work fine.

Note 2: I assume you've figured out how to speak the UDP-based data and camera stream protocols (camera stream is essentially WPILib format except in separate UDP packets, data is all the variables as 64-bit floats packed into a packet with a byte to tell the robot what type of data it is - boiler or gear. It's all in Communications.java). If not, or you have any more questions, feel free to ask 😄

**Comment by qp910** [comment]
I use xiaomi  mobile phone ,copy three  files to /storage/emulated/0 ,  it still doesn't work and the same problem,but now I'm interested in heart rate monitoring through opencv, do you know the principle,I don't have anything on GitHub

**Comment by xeniarose** [comment]
You also need to explicitly give the app storage and camera permissions - I haven't gotten around to making it ask. I don't know anything about heart rate monitoring. Are you associated with an FRC team?

**Comment by qp910** [comment]
no, I'm just a Android developer.my boss asked me to do it.but i don't know, do you have any suggestions?  It is similar to http://www.liqucn.com/rj/30528.shtml......
